### ISSUE TITLE
this is awesome

### ISSUE THREAD

**Issue by nacho-cheeze** [KasRoudra/KasRoudra#7]
honestly man your one of the best users ive seen on this site all your shit is so useful especially maxphisher and the fact that you dont just abandon your project after like six months and ur actually still active blows my mind. its rare to see users like .honestly man if i had money and would donate $200 minimum cuase u deserve but im broke af. but still dude keep it up

**Comment by KasRoudra** [comment]
@nacho-cheeze Your words are a great inspiration to me. Keep me in prayers so that I can continue maintaining those. Have a good day!
